site_name: My Docs
theme:
  name: material
  features:
   - search.suggest
   - search.highlight
   - content.tabs.link 

nav:
  - Introduction: "index.md"
  - AWS: "pages/AWS.md"
  - Conditional State: "pages/ConditionalState.md"
  - Counter Persistent Data: "pages/CounterPersistentData.md"
  - ForEach: "pages/ForEach.md"
  - Greeting: "pages/Greeting.md"
  - Greeting event listener: "pages/GreetingEventListener.md"
  - InputConvert: "pages/InputConvert.md"
  - Request external API: "pages/RequestExternalAPI.md"
  - Solving Math Expression: "pages/SolvingMathExpression.md"
  - Variable Mime Type: "pages/VariableMimeType.md"


  # - Tutorial:
    # - Tutorial Subsection: "pages/tutorial/tutorial_subsection.md"
  - About: "pages/About.md"
  - FAQ: "pages/faq.md"
